#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug  2 15:59:56 2019

@author: stats11
"""
import sys
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import oas_file_handling as oas
import seaborn as sns

f = oas.oas_file("Vander_Heiden_2017_Heavy_HD09_IGHG_HD09_Unsorted_Bcells_age31_healthy_iglblastn_igblastn_IGHG.json.gz")
#f = oas.oas_file("Corcoran_2016_heavy_mouse_IGHG_mouse_heavy_M2_igblastn_igblastn_IGHG.json.gz")
#f = oas.oas_file(str(sys.argv[1]))
if len(sys.argv) > 2:
    threshold = int(sys.argv[2])
else:
    threshold = 1

for region_name in f.regions:
    raw_data = {}
    for amino_acid in f.amino_acids:
        raw_data[amino_acid] = []
        for position in f.region_positions(region_name, threshold):
            amino_acid_frequency = f.amino_acid_frequency(position)
            if amino_acid in amino_acid_frequency:
                raw_data[amino_acid].append(amino_acid_frequency[amino_acid])
            else:
                raw_data[amino_acid].append(0)
  
    df = pd.DataFrame(raw_data)
    df = df.transpose()
    plt.figure(figsize=(10,5))
    sns.heatmap(df.corr())