#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 23 14:32:52 2019

@author: stats11
"""
import os,gzip,json

class oas_file():
    def __init__(self, src): 
        meta_line = True
        seq_data = []
        for line in gzip.open(src,'rb'):
            if meta_line == True:
                    self.metadata = json.loads(line)
                    meta_line=False
                    continue
            #Parse actual sequence data.
            basic_data = json.loads(line)
            seq_data.append(basic_data)
            
            #IMGT-Numbered sequence.
            d = json.loads(basic_data['data'])
            seq_data[-1]['data'] = d
        self.unique_sequences = len(seq_data)
        self.sequence_data = seq_data
